[[item]]
file = '~/.config/fzf/theme'
template = 'fzf'
rewrite = true

[[item]]
file = '~/.config/kitty/theme.conf'
template = 'kitty'
subtemplate = 'default-256'
rewrite = true

[[item]]
file = '~/.config/hexchat/colors.conf'
template = 'hexchat'
rewrite = true

[[item]]
file = '~/.vim/colors/base16.vim'
template = 'vim'
rewrite = true
