[[item]]
file = '~/.config/alacritty/alacritty.yml'
template = 'alacritty'
subtemplate = 'default-256'

[[item]]
file = '~/.config/fzf/theme'
template = 'fzf'
rewrite = true

[[item]]
file = '~/.config/hexchat/colors.conf'
template = 'hexchat'
rewrite = true

[[item]]
file = '~/.vim/colors/base16.vim'
template = 'vim'
rewrite = true
