[[item]]
file = '~/.config/bat/themes/base16-dynamic.tmTheme'
template = 'textmate'
hook = 'bat cache --build'
rewrite = true

[[item]]
file = '~/.config/fzf/theme'
template = 'fzf'
rewrite = true

[[item]]
file = '~/.config/kitty/theme.conf'
template = 'kitty'
hook = 'kitty @ set-colors -a -c ~/.config/kitty/theme.conf'
rewrite = true

[[item]]
file = '~/.config/hexchat/colors.conf'
template = 'hexchat'
rewrite = true
